apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - ../../../../../../components/template
#       value: clusters/overlays/example-cluster/components/application-gitops/overlay/

- ../../../../public/cluster-config/components/template

patches:
- patch: |-
    - op: add
      path: /metadata/labels/gitops.ownedBy
      value: cluster-config
  target:
    group: argoproj.io
    kind: Application
    name: replaceme
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/source/targetRevision
      value: main
  target:
    group: argoproj.io
    kind: Application
    name: replaceme
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/source/path
      value: cluster-config/application-gitops/overlay/
  target:
    group: argoproj.io
    kind: Application
    name: replaceme
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: git@github.com:salanisor/public.git
  target:
    group: argoproj.io
    kind: Application
    name: replaceme
    version: v1alpha1
- patch: |-
    - op: replace
      path: /metadata/name
      value: application-gitops
  target:
    group: argoproj.io
    kind: Application
    name: replaceme
    version: v1alpha1