apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dns-search
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0-0
  desiredState:
    dns-resolver:
      config:
        search:
        - example.com
        - example.org
        server:
        - 8.8.8.8
        - 8.8.4.4
    interfaces:
    - name: 'Wired Connection 1'
      type: ethernet
      state: up
      ipv4:
        auto-dns: false
        enabled: true
        dhcp: true
