apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
  labels:
    app.kubernetes.io/instance: local-storage-operator
spec:
  deviceInclusionSpec:
    deviceTypes:
      - disk
    minSize: 1Gi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: node-role.kubernetes.io/storage
            operator: In
            values:
              - ''
  storageClassName: local-filesystem
  volumeMode: Filesystem
