apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
  labels:
    app.kubernetes.io/instance: local-storage-operator
spec:
  deviceInclusionSpec:
    deviceTypes:
      - disk
    minSize: 1Gi
  tolerations:
  - key: "infra"
    value: "reserved"
    effect: NoExecute
  - key: "infra"
    value: "reserved"
    effect: NoSchedule
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: node-role.kubernetes.io/infra=
            operator: In
            values:
              - ''
  storageClassName: local-filesystem
  volumeMode: Filesystem
