apiVersion: v1
kind: PersistentVolumeClaim
  labels:
    app: noobaa
    noobaa-db: postgres
  name: db-noobaa-db-pg-0
  namespace: openshift-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: thin
  volumeMode: Filesystem
