apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: {}
  labels: {}
  name: replaceme
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: replaceme
    repoURL: replaceme
    targetRevision: replaceme
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
