apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- git@github.com:salanisor/public.git/cluster-config/components/infra/application-gitops-remote/overlays/shared?ref=main

patches:
- patch: |-
    - op: add
      path: "/spec/rbac"
      value:
        defaultPolicy: role:readonly
        policy: |
          g, k8s-prod-admin, role:admin
          g, system:cluster-admins, role:admin
        scopes: "[groups]"
  target:
    group: argoproj.io
    kind: ArgoCD
    name: openshift-gitops
    version: v1beta1

- patch: |-
    - op: add
      path: "/spec/repo/env"
      value:
        - name: SSL_CERT_DIR
          value: "/app/config/tls/"
  target:
    group: argoproj.io
    kind: ArgoCD
    name: openshift-gitops
    version: v1beta1

- patch: |-
    - op: add
      path: "/spec/server/env"
      value:
        - name: SSL_CERT_DIR
          value: "/app/config/tls/"
  target:
    group: argoproj.io
    kind: ArgoCD
    name: openshift-gitops
    version: v1beta1
