apiVersion: v1
data:
  rtfx-test.example.com: |-
    -----BEGIN CERTIFICATE-----
    MIIGfjCCBGagAwIBAgIRAPOK1pq5B7njkBGWIE5gEkAwDQYJKoZIhvcNAQELBQAw
    bDELMAkGA1UEBhMCVVMxIDAeBgNVBAoTF0FtZXJpY2FuIEVsZWN0cmljIFBvd2Vy
    MSIwIAYDVQQLExlDZXJ0aWZpY2F0aW9uIEF1dGhvcml0aWVzMRcwFQYDVQQDEw5S
    U0EgSXNzdWluZyBDQTAeFw0yMzExMTAyMDA0NDRaFw0yNDEyMTAyMDM0NDRaMGMx
    CzAJBgNVBAYTAlVTMSAwHgYDVQQKExdBbWVyaWNhbiBFbGVjdHJpYyBQb3dlcjEU
    MBIGA1UECxMLVExTIFNlcnZlcnMxHDAaBgNVBAMTE3J0ZngtdGVzdC5hZXBzYy5j
    b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlZHroSFgnlPpKMLEK
    9h2uS7ZkEAvYaXqsUNBwcDpvhC7pCGEYZmM1Yf4vF8d+8DYURXR+snhwXn
    vX6yx3QuHalkJnxbZ1JPmGpKusSjGEsedphEZSST4v1fUW9UqyqRX4M+EYGpPn3e
    ZrGbOcMce0XCNwzHpOZ+5rbTARZfwN+9snIRzTMV5INuSxizsGMWMes4Io8G6Z5z
    65IsaFY9rgI14FVFrAcpBd7CQW/k4RqiA6ZxbutaANJKFJZCoNAL91OJJmkMpRTW
    eFE/DXSnijPdMsole8lI2GOgpqdfsJoUJObnzQHZvWKXERY3qBUEXaO69s830X47
    SYPLAgMBAAGjggIiMIICHjBABgNVHREEOTA3ghNydGZ4LXRlc3QuYWVwc2MuY29t
    gglydGZ4LCFSoucnRmeC10ZXN0LmFlcHNjLmNvbTALBgNVHQ8EBAMCBaAw
    HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMFIGCCsGAQUFBwEBBEYwRDBC
    BggrBgEFBQcwAoY2aHR0cDovL2NybC5hZXBzYy5jb20vQUlBL0NlcnRzSXNzdWVk
    dG9SU0FJc3N1aW5nQ0EucDdjMFMGA1UdIARMMEowSAYKYIZIAYb6bAoBAjA6MDgG
    CCsGAQUFBwIBFixodHRwOi8vY3JsLmFlcHNjLmNvbS9Qb2xpY2llcy9BRVAtUEtJ
    LUNQLnBkZjCBxAYDVR0fBIG8MIG5MDCgLqAshipodHRwOi8vY3JsLmFlcHNjLmNv
    bS9DUkxzL1JTQUlzc3VpbmdDQS5jcmwwgYSggYGgf6R9MHsxCzAJBgNVBAYTAlVT
    MSAwHgYDVQQKExdBbWVyaWNhbiBFbGVjdHJpYyBQb3dlcjEiMCAGA1UECxMZQ2Vy
    dGlmaWNhdGlvbiBBdXRob3JpdGllczEXMBUGA1UEAxMOUlNBIElzc3VpbmcgQ0Ex
    DTALBgNVBAMTBENSTDIwHwYDVR0jBBgwFoAU0eUdWp7cCMiQGocDPgvdM9SVIdEw
    HQYDVR0OBBYEFOnrZakIFJOxgQw3PwmN1As/Pe1JMA0GCSqGSIb3DQEBCwUAA4IC
    AQCgWeOYjA20tg3pZoyPou7ungu6iJkQ3bYWWESuEYRce0oz91AXA7bE3zpxDt4d
    aBTZ2WTFbNltCJepgcBUPQYgzFbEEjKVJV5SIQGFGB++IqGXGp59+l1OVaqHCcXd
    qXut2+A0T7AbDs0Dr7vltdUDKCble8wp3DWjD4GX+4rgPn/ulHPUbiwpMO14oocY
    9rxdWS/vTpDPUzXXsdgIoeZL7iu9uOxP1f8m121P9gvejfYM+jEs6uhCXSS0gz/T
    HPSU8KXOX0ZC4EpXOd8ua3dpW036g0rGrcpqwDeDGwGN8NP7DwGt+NaJ6Unnxc3n
    Gfoh39Yd9k89Q7hp1OJQsI7HaAIlGVs96NlgbqI0kdKJGbnEZxvGbgZQy+aiJwWm
    VMvY7RIwzAjFivuSEG+/CiIK3irPgibHNUvoNvZX9CYTZBKar3HOgIEGVterDfrr
    H8vh8qrnXINqDVDQqgGJ0CSSpWan94LsaUSSUFJLH3QkqFRTa11vcYRIyNqz17nM
    zaW3Hx3nfjDoOlFZz4jZARbT4uPDbQqcv2pdSJnd0MZ1idl7p4MTKCDO4Nizf7Js
    2cRjxynJtM8vaZb2vTVy+CCoFkP8zX6o3F+KFbJyfEQbJTBdbWpJTaZ8hzss31rR
    8JZwgyxw5aE+S6Jdruznx6MgXhQQvLj5QwQWXHfeheV7Nw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-tls-certs-cm
  namespace: openshift-gitops