# Defaults for namespaces to avoid repetition
default:
    # Destination for Argo CD (i.e. server)
    argocd:
      cluster:
        name: in-cluster
    # Annotations applied to all namespaces, merged with annotations defined on namespace
    annotations:
      app.openshift.io/vcs-uri: https://bitbucket.msu.edu/ORG/openshift-helm
      app.openshift.io/vcs-ref: main
    # Labels applied to all namespaces, merged with labels defined on namespace
    labels:
      argocd.argoproj.io/managed-by: infra
    networkPolicy: true

# Configuration for shared Argo CD, generates AppProject to cover tenant requirements
argocd:
  # Namespace where the tenant Argo CD is located, if
  # set an AppProject for the tenant will be created
  namespace: openshift-gitops
  # Repositories the tenant is limited to
  sourceRepos:
    - '*'

namespace:
  corp-dev-jboss:
    quota:
      default_cpu: "10m"
      default_memory: "25Mi"
      pods: "6"
      cpu_max: "1"
      cpu_min: ".5"
      memory_max: "10.5Mi"
      memory_min: "2Mi"
    # annotations:
    #   app.openshift.io/vcs-uri: https://github.domain.com/ORG/openshift-two
    #   app.openshift.io/vcs-ref: main
    # Default rbac for all projects, could be overridden on a namespace by namespace level
    # adminGroups, editGroups and viewGroups will be granted admin, edit, view cluster roles respectively
    rbac:
      editGroups:
        - k8s-dev-corp-group