apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-monitoring-config-cm.yaml
# optional, if you want to help reduce the load on the default platform Alertmanager.
# or to specify Prometheus or ThanosRuler retention periods or resources limits.
#- user-workload-monitoring-config.yaml # optional, if you want to help reduce the load on the default platform Alertmanager.
