global:
  resolve_timeout: 5m
  smtp_from: openshift@bastion.ocp4.example.com
  smtp_smarthost: 'mail.ocp4.example.com:25'
  smtp_hello: openshift@bastion.ocp4.example.com
  smtp_require_tls: false
  smtp_auth_username: 'user'
  smtp_auth_password: 'password'
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Critical
    email_configs:
      - to: apps@bastion.ocp4.example.com
        from: openshift@bastion.ocp4.example.com
        smarthost: 'mail.ocp4.example.com:25'
        hello: ocp4.example.com
        require_tls: false
  - name: Default
  - name: 'null'
  - name: Watchdog
  - name: Warning
    email_configs:
      - to: infra@bastion.ocp4.example.com
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - receiver: Critical
      continue: true
      matchers:
        - severity = critical
    - receiver: Warning
      matchers:
        - severity = warning